/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.35
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxinc/eZmax-SDK-csharp-netcore.Api;
using eZmaxinc/eZmax-SDK-csharp-netcore.Model;
using eZmaxinc/eZmax-SDK-csharp-netcore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxinc/eZmax-SDK-csharp-netcore.Test.Model
{
    /// <summary>
    ///  Class for testing ApikeyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApikeyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApikeyResponse
        //private ApikeyResponse instance;

        public ApikeyResponseTests()
        {
            // TODO uncomment below to create an instance of ApikeyResponse
            //instance = new ApikeyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApikeyResponse
        /// </summary>
        [Fact]
        public void ApikeyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApikeyResponse
            //Assert.IsType<ApikeyResponse>(instance);
        }


        /// <summary>
        /// Test the property 'objApikeyDescription'
        /// </summary>
        [Fact]
        public void objApikeyDescriptionTest()
        {
            // TODO unit test for the property 'objApikeyDescription'
        }
        /// <summary>
        /// Test the property 'sComputedToken'
        /// </summary>
        [Fact]
        public void sComputedTokenTest()
        {
            // TODO unit test for the property 'sComputedToken'
        }
        /// <summary>
        /// Test the property 'pkiApikeyID'
        /// </summary>
        [Fact]
        public void pkiApikeyIDTest()
        {
            // TODO unit test for the property 'pkiApikeyID'
        }
        /// <summary>
        /// Test the property 'objAudit'
        /// </summary>
        [Fact]
        public void objAuditTest()
        {
            // TODO unit test for the property 'objAudit'
        }

    }

}
