/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxinc/eZmax-SDK-csharp-netcore.Api;
using eZmaxinc/eZmax-SDK-csharp-netcore.Model;
using eZmaxinc/eZmax-SDK-csharp-netcore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxinc/eZmax-SDK-csharp-netcore.Test.Model
{
    /// <summary>
    ///  Class for testing CommonResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommonResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommonResponse
        //private CommonResponse instance;

        public CommonResponseTests()
        {
            // TODO uncomment below to create an instance of CommonResponse
            //instance = new CommonResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommonResponse
        /// </summary>
        [Fact]
        public void CommonResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommonResponse
            //Assert.IsType<CommonResponse>(instance);
        }


        /// <summary>
        /// Test the property 'objDebugPayload'
        /// </summary>
        [Fact]
        public void objDebugPayloadTest()
        {
            // TODO unit test for the property 'objDebugPayload'
        }
        /// <summary>
        /// Test the property 'objDebug'
        /// </summary>
        [Fact]
        public void objDebugTest()
        {
            // TODO unit test for the property 'objDebug'
        }

    }

}
