/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.37
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxinc/eZmax-SDK-csharp-netcore.Api;
using eZmaxinc/eZmax-SDK-csharp-netcore.Model;
using eZmaxinc/eZmax-SDK-csharp-netcore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxinc/eZmax-SDK-csharp-netcore.Test.Model
{
    /// <summary>
    ///  Class for testing EzsignfolderSendV1Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsignfolderSendV1RequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EzsignfolderSendV1Request
        //private EzsignfolderSendV1Request instance;

        public EzsignfolderSendV1RequestTests()
        {
            // TODO uncomment below to create an instance of EzsignfolderSendV1Request
            //instance = new EzsignfolderSendV1Request();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EzsignfolderSendV1Request
        /// </summary>
        [Fact]
        public void EzsignfolderSendV1RequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EzsignfolderSendV1Request
            //Assert.IsType<EzsignfolderSendV1Request>(instance);
        }


        /// <summary>
        /// Test the property 'tExtraMessage'
        /// </summary>
        [Fact]
        public void tExtraMessageTest()
        {
            // TODO unit test for the property 'tExtraMessage'
        }

    }

}
