/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.37
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxinc/eZmax-SDK-csharp-netcore.Api;
using eZmaxinc/eZmax-SDK-csharp-netcore.Model;
using eZmaxinc/eZmax-SDK-csharp-netcore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxinc/eZmax-SDK-csharp-netcore.Test.Model
{
    /// <summary>
    ///  Class for testing EzsigndocumentGetDownloadUrlV1ResponseMPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsigndocumentGetDownloadUrlV1ResponseMPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EzsigndocumentGetDownloadUrlV1ResponseMPayload
        //private EzsigndocumentGetDownloadUrlV1ResponseMPayload instance;

        public EzsigndocumentGetDownloadUrlV1ResponseMPayloadTests()
        {
            // TODO uncomment below to create an instance of EzsigndocumentGetDownloadUrlV1ResponseMPayload
            //instance = new EzsigndocumentGetDownloadUrlV1ResponseMPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EzsigndocumentGetDownloadUrlV1ResponseMPayload
        /// </summary>
        [Fact]
        public void EzsigndocumentGetDownloadUrlV1ResponseMPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" EzsigndocumentGetDownloadUrlV1ResponseMPayload
            //Assert.IsType<EzsigndocumentGetDownloadUrlV1ResponseMPayload>(instance);
        }


        /// <summary>
        /// Test the property 'sDownloadUrl'
        /// </summary>
        [Fact]
        public void sDownloadUrlTest()
        {
            // TODO unit test for the property 'sDownloadUrl'
        }

    }

}
