/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.37
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxinc/eZmax-SDK-csharp-netcore.Api;
using eZmaxinc/eZmax-SDK-csharp-netcore.Model;
using eZmaxinc/eZmax-SDK-csharp-netcore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxinc/eZmax-SDK-csharp-netcore.Test.Model
{
    /// <summary>
    ///  Class for testing UserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserResponse
        //private UserResponse instance;

        public UserResponseTests()
        {
            // TODO uncomment below to create an instance of UserResponse
            //instance = new UserResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserResponse
        /// </summary>
        [Fact]
        public void UserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserResponse
            //Assert.IsType<UserResponse>(instance);
        }


        /// <summary>
        /// Test the property 'pkiUserID'
        /// </summary>
        [Fact]
        public void pkiUserIDTest()
        {
            // TODO unit test for the property 'pkiUserID'
        }
        /// <summary>
        /// Test the property 'fkiLanguageID'
        /// </summary>
        [Fact]
        public void fkiLanguageIDTest()
        {
            // TODO unit test for the property 'fkiLanguageID'
        }
        /// <summary>
        /// Test the property 'eUserType'
        /// </summary>
        [Fact]
        public void eUserTypeTest()
        {
            // TODO unit test for the property 'eUserType'
        }
        /// <summary>
        /// Test the property 'sUserFirstname'
        /// </summary>
        [Fact]
        public void sUserFirstnameTest()
        {
            // TODO unit test for the property 'sUserFirstname'
        }
        /// <summary>
        /// Test the property 'sUserLastname'
        /// </summary>
        [Fact]
        public void sUserLastnameTest()
        {
            // TODO unit test for the property 'sUserLastname'
        }
        /// <summary>
        /// Test the property 'sUserLoginname'
        /// </summary>
        [Fact]
        public void sUserLoginnameTest()
        {
            // TODO unit test for the property 'sUserLoginname'
        }
        /// <summary>
        /// Test the property 'objAudit'
        /// </summary>
        [Fact]
        public void objAuditTest()
        {
            // TODO unit test for the property 'objAudit'
        }

    }

}
