/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxinc/eZmax-SDK-csharp-netcore.Api;
using eZmaxinc/eZmax-SDK-csharp-netcore.Model;
using eZmaxinc/eZmax-SDK-csharp-netcore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxinc/eZmax-SDK-csharp-netcore.Test.Model
{
    /// <summary>
    ///  Class for testing UserCreateEzsignuserV1Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserCreateEzsignuserV1ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserCreateEzsignuserV1Response
        //private UserCreateEzsignuserV1Response instance;

        public UserCreateEzsignuserV1ResponseTests()
        {
            // TODO uncomment below to create an instance of UserCreateEzsignuserV1Response
            //instance = new UserCreateEzsignuserV1Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserCreateEzsignuserV1Response
        /// </summary>
        [Fact]
        public void UserCreateEzsignuserV1ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserCreateEzsignuserV1Response
            //Assert.IsType<UserCreateEzsignuserV1Response>(instance);
        }


        /// <summary>
        /// Test the property 'mPayload'
        /// </summary>
        [Fact]
        public void mPayloadTest()
        {
            // TODO unit test for the property 'mPayload'
        }
        /// <summary>
        /// Test the property 'objDebugPayload'
        /// </summary>
        [Fact]
        public void objDebugPayloadTest()
        {
            // TODO unit test for the property 'objDebugPayload'
        }
        /// <summary>
        /// Test the property 'objDebug'
        /// </summary>
        [Fact]
        public void objDebugTest()
        {
            // TODO unit test for the property 'objDebug'
        }

    }

}
