/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.37
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxinc/eZmax-SDK-csharp-netcore.Api;
using eZmaxinc/eZmax-SDK-csharp-netcore.Model;
using eZmaxinc/eZmax-SDK-csharp-netcore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxinc/eZmax-SDK-csharp-netcore.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookUserUserCreatedAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookUserUserCreatedAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookUserUserCreatedAllOf
        //private WebhookUserUserCreatedAllOf instance;

        public WebhookUserUserCreatedAllOfTests()
        {
            // TODO uncomment below to create an instance of WebhookUserUserCreatedAllOf
            //instance = new WebhookUserUserCreatedAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookUserUserCreatedAllOf
        /// </summary>
        [Fact]
        public void WebhookUserUserCreatedAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookUserUserCreatedAllOf
            //Assert.IsType<WebhookUserUserCreatedAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'objUser'
        /// </summary>
        [Fact]
        public void objUserTest()
        {
            // TODO unit test for the property 'objUser'
        }

    }

}
