/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.42
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing ApikeyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApikeyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApikeyRequest
        //private ApikeyRequest instance;

        public ApikeyRequestTests()
        {
            // TODO uncomment below to create an instance of ApikeyRequest
            //instance = new ApikeyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApikeyRequest
        /// </summary>
        [Fact]
        public void ApikeyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApikeyRequest
            //Assert.IsType<ApikeyRequest>(instance);
        }


        /// <summary>
        /// Test the property 'FkiUserID'
        /// </summary>
        [Fact]
        public void FkiUserIDTest()
        {
            // TODO unit test for the property 'FkiUserID'
        }
        /// <summary>
        /// Test the property 'ObjApikeyDescription'
        /// </summary>
        [Fact]
        public void ObjApikeyDescriptionTest()
        {
            // TODO unit test for the property 'ObjApikeyDescription'
        }

    }

}
