/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.43
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing CommonResponseError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommonResponseErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommonResponseError
        //private CommonResponseError instance;

        public CommonResponseErrorTests()
        {
            // TODO uncomment below to create an instance of CommonResponseError
            //instance = new CommonResponseError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommonResponseError
        /// </summary>
        [Fact]
        public void CommonResponseErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommonResponseError
            //Assert.IsType<CommonResponseError>(instance);
        }


        /// <summary>
        /// Test the property 'SErrorMessage'
        /// </summary>
        [Fact]
        public void SErrorMessageTest()
        {
            // TODO unit test for the property 'SErrorMessage'
        }
        /// <summary>
        /// Test the property 'EErrorCode'
        /// </summary>
        [Fact]
        public void EErrorCodeTest()
        {
            // TODO unit test for the property 'EErrorCode'
        }

    }

}
