/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.40
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing EzsignfoldersignerassociationCreateObjectV1Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsignfoldersignerassociationCreateObjectV1ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EzsignfoldersignerassociationCreateObjectV1Response
        //private EzsignfoldersignerassociationCreateObjectV1Response instance;

        public EzsignfoldersignerassociationCreateObjectV1ResponseTests()
        {
            // TODO uncomment below to create an instance of EzsignfoldersignerassociationCreateObjectV1Response
            //instance = new EzsignfoldersignerassociationCreateObjectV1Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EzsignfoldersignerassociationCreateObjectV1Response
        /// </summary>
        [Fact]
        public void EzsignfoldersignerassociationCreateObjectV1ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EzsignfoldersignerassociationCreateObjectV1Response
            //Assert.IsType<EzsignfoldersignerassociationCreateObjectV1Response>(instance);
        }


        /// <summary>
        /// Test the property 'MPayload'
        /// </summary>
        [Fact]
        public void MPayloadTest()
        {
            // TODO unit test for the property 'MPayload'
        }
        /// <summary>
        /// Test the property 'ObjDebugPayload'
        /// </summary>
        [Fact]
        public void ObjDebugPayloadTest()
        {
            // TODO unit test for the property 'ObjDebugPayload'
        }
        /// <summary>
        /// Test the property 'ObjDebug'
        /// </summary>
        [Fact]
        public void ObjDebugTest()
        {
            // TODO unit test for the property 'ObjDebug'
        }

    }

}
