/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.41
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing EzsigndocumentCreateObjectV1ResponseMPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsigndocumentCreateObjectV1ResponseMPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EzsigndocumentCreateObjectV1ResponseMPayload
        //private EzsigndocumentCreateObjectV1ResponseMPayload instance;

        public EzsigndocumentCreateObjectV1ResponseMPayloadTests()
        {
            // TODO uncomment below to create an instance of EzsigndocumentCreateObjectV1ResponseMPayload
            //instance = new EzsigndocumentCreateObjectV1ResponseMPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EzsigndocumentCreateObjectV1ResponseMPayload
        /// </summary>
        [Fact]
        public void EzsigndocumentCreateObjectV1ResponseMPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" EzsigndocumentCreateObjectV1ResponseMPayload
            //Assert.IsType<EzsigndocumentCreateObjectV1ResponseMPayload>(instance);
        }


        /// <summary>
        /// Test the property 'APkiEzsigndocumentID'
        /// </summary>
        [Fact]
        public void APkiEzsigndocumentIDTest()
        {
            // TODO unit test for the property 'APkiEzsigndocumentID'
        }

    }

}
