/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.44
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing EzsignsignerRequestCompoundContact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsignsignerRequestCompoundContactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EzsignsignerRequestCompoundContact
        //private EzsignsignerRequestCompoundContact instance;

        public EzsignsignerRequestCompoundContactTests()
        {
            // TODO uncomment below to create an instance of EzsignsignerRequestCompoundContact
            //instance = new EzsignsignerRequestCompoundContact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EzsignsignerRequestCompoundContact
        /// </summary>
        [Fact]
        public void EzsignsignerRequestCompoundContactInstanceTest()
        {
            // TODO uncomment below to test "IsType" EzsignsignerRequestCompoundContact
            //Assert.IsType<EzsignsignerRequestCompoundContact>(instance);
        }


        /// <summary>
        /// Test the property 'SContactFirstname'
        /// </summary>
        [Fact]
        public void SContactFirstnameTest()
        {
            // TODO unit test for the property 'SContactFirstname'
        }
        /// <summary>
        /// Test the property 'SContactLastname'
        /// </summary>
        [Fact]
        public void SContactLastnameTest()
        {
            // TODO unit test for the property 'SContactLastname'
        }
        /// <summary>
        /// Test the property 'FkiLanguageID'
        /// </summary>
        [Fact]
        public void FkiLanguageIDTest()
        {
            // TODO unit test for the property 'FkiLanguageID'
        }
        /// <summary>
        /// Test the property 'SEmailAddress'
        /// </summary>
        [Fact]
        public void SEmailAddressTest()
        {
            // TODO unit test for the property 'SEmailAddress'
        }
        /// <summary>
        /// Test the property 'SPhoneNumber'
        /// </summary>
        [Fact]
        public void SPhoneNumberTest()
        {
            // TODO unit test for the property 'SPhoneNumber'
        }
        /// <summary>
        /// Test the property 'SPhoneNumberCell'
        /// </summary>
        [Fact]
        public void SPhoneNumberCellTest()
        {
            // TODO unit test for the property 'SPhoneNumberCell'
        }

    }

}
