/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.42
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing FieldEEzsignfolderStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FieldEEzsignfolderStepTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FieldEEzsignfolderStep
        //private FieldEEzsignfolderStep instance;

        public FieldEEzsignfolderStepTests()
        {
            // TODO uncomment below to create an instance of FieldEEzsignfolderStep
            //instance = new FieldEEzsignfolderStep();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FieldEEzsignfolderStep
        /// </summary>
        [Fact]
        public void FieldEEzsignfolderStepInstanceTest()
        {
            // TODO uncomment below to test "IsType" FieldEEzsignfolderStep
            //Assert.IsType<FieldEEzsignfolderStep>(instance);
        }



    }

}
