/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.41
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing UNUSEDEzsignfolderEditObjectV1Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UNUSEDEzsignfolderEditObjectV1RequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UNUSEDEzsignfolderEditObjectV1Request
        //private UNUSEDEzsignfolderEditObjectV1Request instance;

        public UNUSEDEzsignfolderEditObjectV1RequestTests()
        {
            // TODO uncomment below to create an instance of UNUSEDEzsignfolderEditObjectV1Request
            //instance = new UNUSEDEzsignfolderEditObjectV1Request();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UNUSEDEzsignfolderEditObjectV1Request
        /// </summary>
        [Fact]
        public void UNUSEDEzsignfolderEditObjectV1RequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UNUSEDEzsignfolderEditObjectV1Request
            //Assert.IsType<UNUSEDEzsignfolderEditObjectV1Request>(instance);
        }


        /// <summary>
        /// Test the property 'ObjEzsignfolder'
        /// </summary>
        [Fact]
        public void ObjEzsignfolderTest()
        {
            // TODO unit test for the property 'ObjEzsignfolder'
        }

    }

}
