/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.46
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing UserResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserResponseAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserResponseAllOf
        //private UserResponseAllOf instance;

        public UserResponseAllOfTests()
        {
            // TODO uncomment below to create an instance of UserResponseAllOf
            //instance = new UserResponseAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserResponseAllOf
        /// </summary>
        [Fact]
        public void UserResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserResponseAllOf
            //Assert.IsType<UserResponseAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'PkiUserID'
        /// </summary>
        [Fact]
        public void PkiUserIDTest()
        {
            // TODO unit test for the property 'PkiUserID'
        }
        /// <summary>
        /// Test the property 'FkiLanguageID'
        /// </summary>
        [Fact]
        public void FkiLanguageIDTest()
        {
            // TODO unit test for the property 'FkiLanguageID'
        }
        /// <summary>
        /// Test the property 'EUserType'
        /// </summary>
        [Fact]
        public void EUserTypeTest()
        {
            // TODO unit test for the property 'EUserType'
        }
        /// <summary>
        /// Test the property 'SUserFirstname'
        /// </summary>
        [Fact]
        public void SUserFirstnameTest()
        {
            // TODO unit test for the property 'SUserFirstname'
        }
        /// <summary>
        /// Test the property 'SUserLastname'
        /// </summary>
        [Fact]
        public void SUserLastnameTest()
        {
            // TODO unit test for the property 'SUserLastname'
        }
        /// <summary>
        /// Test the property 'SUserLoginname'
        /// </summary>
        [Fact]
        public void SUserLoginnameTest()
        {
            // TODO unit test for the property 'SUserLoginname'
        }
        /// <summary>
        /// Test the property 'ObjAudit'
        /// </summary>
        [Fact]
        public void ObjAuditTest()
        {
            // TODO unit test for the property 'ObjAudit'
        }

    }

}
