/*
 * eZmax API Definition
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.40
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookResponse
        //private WebhookResponse instance;

        public WebhookResponseTests()
        {
            // TODO uncomment below to create an instance of WebhookResponse
            //instance = new WebhookResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookResponse
        /// </summary>
        [Fact]
        public void WebhookResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookResponse
            //Assert.IsType<WebhookResponse>(instance);
        }


        /// <summary>
        /// Test the property 'PkiWebhookID'
        /// </summary>
        [Fact]
        public void PkiWebhookIDTest()
        {
            // TODO unit test for the property 'PkiWebhookID'
        }
        /// <summary>
        /// Test the property 'EWebhookModule'
        /// </summary>
        [Fact]
        public void EWebhookModuleTest()
        {
            // TODO unit test for the property 'EWebhookModule'
        }
        /// <summary>
        /// Test the property 'EWebhookEzsignevent'
        /// </summary>
        [Fact]
        public void EWebhookEzsigneventTest()
        {
            // TODO unit test for the property 'EWebhookEzsignevent'
        }
        /// <summary>
        /// Test the property 'PksCustomerCode'
        /// </summary>
        [Fact]
        public void PksCustomerCodeTest()
        {
            // TODO unit test for the property 'PksCustomerCode'
        }
        /// <summary>
        /// Test the property 'SWebhookUrl'
        /// </summary>
        [Fact]
        public void SWebhookUrlTest()
        {
            // TODO unit test for the property 'SWebhookUrl'
        }
        /// <summary>
        /// Test the property 'SWebhookEmailfailed'
        /// </summary>
        [Fact]
        public void SWebhookEmailfailedTest()
        {
            // TODO unit test for the property 'SWebhookEmailfailed'
        }
        /// <summary>
        /// Test the property 'EWebhookManagementevent'
        /// </summary>
        [Fact]
        public void EWebhookManagementeventTest()
        {
            // TODO unit test for the property 'EWebhookManagementevent'
        }

    }

}
